#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class testLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDATA(DATA instance);
    partial void UpdateDATA(DATA instance);
    partial void DeleteDATA(DATA instance);
    partial void InsertOPERATOR(OPERATOR instance);
    partial void UpdateOPERATOR(OPERATOR instance);
    partial void DeleteOPERATOR(OPERATOR instance);
    partial void InsertSTATUS(STATUS instance);
    partial void UpdateSTATUS(STATUS instance);
    partial void DeleteSTATUS(STATUS instance);
    #endregion
		
		public testLINQDataContext() : 
				base(global::Report.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public testLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public testLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DATA> DATAs
		{
			get
			{
				return this.GetTable<DATA>();
			}
		}
		
		public System.Data.Linq.Table<OPERATOR> OPERATORs
		{
			get
			{
				return this.GetTable<OPERATOR>();
			}
		}
		
		public System.Data.Linq.Table<STATUS> STATUS
		{
			get
			{
				return this.GetTable<STATUS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DATA")]
	public partial class DATA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Date_Time;
		
		private System.Nullable<float> _Value1;
		
		private System.Nullable<byte> _Status1;
		
		private System.Nullable<float> _Value2;
		
		private System.Nullable<byte> _Status2;
		
		private System.Nullable<float> _Value3;
		
		private System.Nullable<byte> _Status3;
		
		private System.Nullable<float> _Value4;
		
		private System.Nullable<byte> _Status4;
		
		private System.Nullable<float> _Value5;
		
		private System.Nullable<byte> _Status5;
		
		private System.Nullable<float> _Value6;
		
		private System.Nullable<byte> _Status6;
		
		private System.Nullable<float> _Value7;
		
		private System.Nullable<byte> _Status7;
		
		private System.Nullable<float> _Value8;
		
		private System.Nullable<byte> _Status8;
		
		private System.Nullable<float> _Value9;
		
		private System.Nullable<byte> _Status9;
		
		private System.Nullable<float> _Value10;
		
		private System.Nullable<byte> _Status10;
		
		private System.Nullable<float> _Value11;
		
		private System.Nullable<byte> _Status11;
		
		private System.Nullable<float> _Value12;
		
		private System.Nullable<byte> _Status12;
		
		private System.Nullable<float> _Value13;
		
		private System.Nullable<byte> _Status13;
		
		private System.Nullable<float> _Value14;
		
		private System.Nullable<byte> _Status14;
		
		private System.Nullable<float> _Value15;
		
		private System.Nullable<byte> _Status15;
		
		private System.Nullable<float> _Value16;
		
		private System.Nullable<byte> _Status16;
		
		private System.Nullable<float> _Value17;
		
		private System.Nullable<byte> _Status17;
		
		private System.Nullable<float> _Value18;
		
		private System.Nullable<byte> _Status18;
		
		private System.Nullable<float> _Value19;
		
		private System.Nullable<byte> _Status19;
		
		private System.Nullable<float> _Value20;
		
		private System.Nullable<byte> _Status20;
		
		private System.Nullable<float> _Value21;
		
		private System.Nullable<byte> _Status21;
		
		private System.Nullable<float> _Value22;
		
		private System.Nullable<byte> _Status22;
		
		private System.Nullable<float> _Value23;
		
		private System.Nullable<byte> _Status23;
		
		private System.Nullable<float> _Value24;
		
		private System.Nullable<byte> _Status24;
		
		private System.Nullable<float> _Value25;
		
		private System.Nullable<byte> _Status25;
		
		private System.Nullable<float> _Value26;
		
		private System.Nullable<byte> _Status26;
		
		private System.Nullable<float> _Value27;
		
		private System.Nullable<byte> _Status27;
		
		private System.Nullable<float> _Value28;
		
		private System.Nullable<byte> _Status28;
		
		private System.Nullable<float> _Value29;
		
		private System.Nullable<byte> _Status29;
		
		private System.Nullable<float> _Value30;
		
		private System.Nullable<byte> _Status30;
		
		private System.Nullable<float> _Value31;
		
		private System.Nullable<byte> _Status31;
		
		private System.Nullable<float> _Value32;
		
		private System.Nullable<byte> _Status32;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDate_TimeChanging(System.DateTime value);
    partial void OnDate_TimeChanged();
    partial void OnValue1Changing(System.Nullable<float> value);
    partial void OnValue1Changed();
    partial void OnStatus1Changing(System.Nullable<byte> value);
    partial void OnStatus1Changed();
    partial void OnValue2Changing(System.Nullable<float> value);
    partial void OnValue2Changed();
    partial void OnStatus2Changing(System.Nullable<byte> value);
    partial void OnStatus2Changed();
    partial void OnValue3Changing(System.Nullable<float> value);
    partial void OnValue3Changed();
    partial void OnStatus3Changing(System.Nullable<byte> value);
    partial void OnStatus3Changed();
    partial void OnValue4Changing(System.Nullable<float> value);
    partial void OnValue4Changed();
    partial void OnStatus4Changing(System.Nullable<byte> value);
    partial void OnStatus4Changed();
    partial void OnValue5Changing(System.Nullable<float> value);
    partial void OnValue5Changed();
    partial void OnStatus5Changing(System.Nullable<byte> value);
    partial void OnStatus5Changed();
    partial void OnValue6Changing(System.Nullable<float> value);
    partial void OnValue6Changed();
    partial void OnStatus6Changing(System.Nullable<byte> value);
    partial void OnStatus6Changed();
    partial void OnValue7Changing(System.Nullable<float> value);
    partial void OnValue7Changed();
    partial void OnStatus7Changing(System.Nullable<byte> value);
    partial void OnStatus7Changed();
    partial void OnValue8Changing(System.Nullable<float> value);
    partial void OnValue8Changed();
    partial void OnStatus8Changing(System.Nullable<byte> value);
    partial void OnStatus8Changed();
    partial void OnValue9Changing(System.Nullable<float> value);
    partial void OnValue9Changed();
    partial void OnStatus9Changing(System.Nullable<byte> value);
    partial void OnStatus9Changed();
    partial void OnValue10Changing(System.Nullable<float> value);
    partial void OnValue10Changed();
    partial void OnStatus10Changing(System.Nullable<byte> value);
    partial void OnStatus10Changed();
    partial void OnValue11Changing(System.Nullable<float> value);
    partial void OnValue11Changed();
    partial void OnStatus11Changing(System.Nullable<byte> value);
    partial void OnStatus11Changed();
    partial void OnValue12Changing(System.Nullable<float> value);
    partial void OnValue12Changed();
    partial void OnStatus12Changing(System.Nullable<byte> value);
    partial void OnStatus12Changed();
    partial void OnValue13Changing(System.Nullable<float> value);
    partial void OnValue13Changed();
    partial void OnStatus13Changing(System.Nullable<byte> value);
    partial void OnStatus13Changed();
    partial void OnValue14Changing(System.Nullable<float> value);
    partial void OnValue14Changed();
    partial void OnStatus14Changing(System.Nullable<byte> value);
    partial void OnStatus14Changed();
    partial void OnValue15Changing(System.Nullable<float> value);
    partial void OnValue15Changed();
    partial void OnStatus15Changing(System.Nullable<byte> value);
    partial void OnStatus15Changed();
    partial void OnValue16Changing(System.Nullable<float> value);
    partial void OnValue16Changed();
    partial void OnStatus16Changing(System.Nullable<byte> value);
    partial void OnStatus16Changed();
    partial void OnValue17Changing(System.Nullable<float> value);
    partial void OnValue17Changed();
    partial void OnStatus17Changing(System.Nullable<byte> value);
    partial void OnStatus17Changed();
    partial void OnValue18Changing(System.Nullable<float> value);
    partial void OnValue18Changed();
    partial void OnStatus18Changing(System.Nullable<byte> value);
    partial void OnStatus18Changed();
    partial void OnValue19Changing(System.Nullable<float> value);
    partial void OnValue19Changed();
    partial void OnStatus19Changing(System.Nullable<byte> value);
    partial void OnStatus19Changed();
    partial void OnValue20Changing(System.Nullable<float> value);
    partial void OnValue20Changed();
    partial void OnStatus20Changing(System.Nullable<byte> value);
    partial void OnStatus20Changed();
    partial void OnValue21Changing(System.Nullable<float> value);
    partial void OnValue21Changed();
    partial void OnStatus21Changing(System.Nullable<byte> value);
    partial void OnStatus21Changed();
    partial void OnValue22Changing(System.Nullable<float> value);
    partial void OnValue22Changed();
    partial void OnStatus22Changing(System.Nullable<byte> value);
    partial void OnStatus22Changed();
    partial void OnValue23Changing(System.Nullable<float> value);
    partial void OnValue23Changed();
    partial void OnStatus23Changing(System.Nullable<byte> value);
    partial void OnStatus23Changed();
    partial void OnValue24Changing(System.Nullable<float> value);
    partial void OnValue24Changed();
    partial void OnStatus24Changing(System.Nullable<byte> value);
    partial void OnStatus24Changed();
    partial void OnValue25Changing(System.Nullable<float> value);
    partial void OnValue25Changed();
    partial void OnStatus25Changing(System.Nullable<byte> value);
    partial void OnStatus25Changed();
    partial void OnValue26Changing(System.Nullable<float> value);
    partial void OnValue26Changed();
    partial void OnStatus26Changing(System.Nullable<byte> value);
    partial void OnStatus26Changed();
    partial void OnValue27Changing(System.Nullable<float> value);
    partial void OnValue27Changed();
    partial void OnStatus27Changing(System.Nullable<byte> value);
    partial void OnStatus27Changed();
    partial void OnValue28Changing(System.Nullable<float> value);
    partial void OnValue28Changed();
    partial void OnStatus28Changing(System.Nullable<byte> value);
    partial void OnStatus28Changed();
    partial void OnValue29Changing(System.Nullable<float> value);
    partial void OnValue29Changed();
    partial void OnStatus29Changing(System.Nullable<byte> value);
    partial void OnStatus29Changed();
    partial void OnValue30Changing(System.Nullable<float> value);
    partial void OnValue30Changed();
    partial void OnStatus30Changing(System.Nullable<byte> value);
    partial void OnStatus30Changed();
    partial void OnValue31Changing(System.Nullable<float> value);
    partial void OnValue31Changed();
    partial void OnStatus31Changing(System.Nullable<byte> value);
    partial void OnStatus31Changed();
    partial void OnValue32Changing(System.Nullable<float> value);
    partial void OnValue32Changed();
    partial void OnStatus32Changing(System.Nullable<byte> value);
    partial void OnStatus32Changed();
    #endregion
		
		public DATA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Time", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date_Time
		{
			get
			{
				return this._Date_Time;
			}
			set
			{
				if ((this._Date_Time != value))
				{
					this.OnDate_TimeChanging(value);
					this.SendPropertyChanging();
					this._Date_Time = value;
					this.SendPropertyChanged("Date_Time");
					this.OnDate_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value1", DbType="Real")]
		public System.Nullable<float> Value1
		{
			get
			{
				return this._Value1;
			}
			set
			{
				if ((this._Value1 != value))
				{
					this.OnValue1Changing(value);
					this.SendPropertyChanging();
					this._Value1 = value;
					this.SendPropertyChanged("Value1");
					this.OnValue1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status1", DbType="TinyInt")]
		public System.Nullable<byte> Status1
		{
			get
			{
				return this._Status1;
			}
			set
			{
				if ((this._Status1 != value))
				{
					this.OnStatus1Changing(value);
					this.SendPropertyChanging();
					this._Status1 = value;
					this.SendPropertyChanged("Status1");
					this.OnStatus1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value2", DbType="Real")]
		public System.Nullable<float> Value2
		{
			get
			{
				return this._Value2;
			}
			set
			{
				if ((this._Value2 != value))
				{
					this.OnValue2Changing(value);
					this.SendPropertyChanging();
					this._Value2 = value;
					this.SendPropertyChanged("Value2");
					this.OnValue2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status2", DbType="TinyInt")]
		public System.Nullable<byte> Status2
		{
			get
			{
				return this._Status2;
			}
			set
			{
				if ((this._Status2 != value))
				{
					this.OnStatus2Changing(value);
					this.SendPropertyChanging();
					this._Status2 = value;
					this.SendPropertyChanged("Status2");
					this.OnStatus2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value3", DbType="Real")]
		public System.Nullable<float> Value3
		{
			get
			{
				return this._Value3;
			}
			set
			{
				if ((this._Value3 != value))
				{
					this.OnValue3Changing(value);
					this.SendPropertyChanging();
					this._Value3 = value;
					this.SendPropertyChanged("Value3");
					this.OnValue3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status3", DbType="TinyInt")]
		public System.Nullable<byte> Status3
		{
			get
			{
				return this._Status3;
			}
			set
			{
				if ((this._Status3 != value))
				{
					this.OnStatus3Changing(value);
					this.SendPropertyChanging();
					this._Status3 = value;
					this.SendPropertyChanged("Status3");
					this.OnStatus3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value4", DbType="Real")]
		public System.Nullable<float> Value4
		{
			get
			{
				return this._Value4;
			}
			set
			{
				if ((this._Value4 != value))
				{
					this.OnValue4Changing(value);
					this.SendPropertyChanging();
					this._Value4 = value;
					this.SendPropertyChanged("Value4");
					this.OnValue4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status4", DbType="TinyInt")]
		public System.Nullable<byte> Status4
		{
			get
			{
				return this._Status4;
			}
			set
			{
				if ((this._Status4 != value))
				{
					this.OnStatus4Changing(value);
					this.SendPropertyChanging();
					this._Status4 = value;
					this.SendPropertyChanged("Status4");
					this.OnStatus4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value5", DbType="Real")]
		public System.Nullable<float> Value5
		{
			get
			{
				return this._Value5;
			}
			set
			{
				if ((this._Value5 != value))
				{
					this.OnValue5Changing(value);
					this.SendPropertyChanging();
					this._Value5 = value;
					this.SendPropertyChanged("Value5");
					this.OnValue5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status5", DbType="TinyInt")]
		public System.Nullable<byte> Status5
		{
			get
			{
				return this._Status5;
			}
			set
			{
				if ((this._Status5 != value))
				{
					this.OnStatus5Changing(value);
					this.SendPropertyChanging();
					this._Status5 = value;
					this.SendPropertyChanged("Status5");
					this.OnStatus5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value6", DbType="Real")]
		public System.Nullable<float> Value6
		{
			get
			{
				return this._Value6;
			}
			set
			{
				if ((this._Value6 != value))
				{
					this.OnValue6Changing(value);
					this.SendPropertyChanging();
					this._Value6 = value;
					this.SendPropertyChanged("Value6");
					this.OnValue6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status6", DbType="TinyInt")]
		public System.Nullable<byte> Status6
		{
			get
			{
				return this._Status6;
			}
			set
			{
				if ((this._Status6 != value))
				{
					this.OnStatus6Changing(value);
					this.SendPropertyChanging();
					this._Status6 = value;
					this.SendPropertyChanged("Status6");
					this.OnStatus6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value7", DbType="Real")]
		public System.Nullable<float> Value7
		{
			get
			{
				return this._Value7;
			}
			set
			{
				if ((this._Value7 != value))
				{
					this.OnValue7Changing(value);
					this.SendPropertyChanging();
					this._Value7 = value;
					this.SendPropertyChanged("Value7");
					this.OnValue7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status7", DbType="TinyInt")]
		public System.Nullable<byte> Status7
		{
			get
			{
				return this._Status7;
			}
			set
			{
				if ((this._Status7 != value))
				{
					this.OnStatus7Changing(value);
					this.SendPropertyChanging();
					this._Status7 = value;
					this.SendPropertyChanged("Status7");
					this.OnStatus7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value8", DbType="Real")]
		public System.Nullable<float> Value8
		{
			get
			{
				return this._Value8;
			}
			set
			{
				if ((this._Value8 != value))
				{
					this.OnValue8Changing(value);
					this.SendPropertyChanging();
					this._Value8 = value;
					this.SendPropertyChanged("Value8");
					this.OnValue8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status8", DbType="TinyInt")]
		public System.Nullable<byte> Status8
		{
			get
			{
				return this._Status8;
			}
			set
			{
				if ((this._Status8 != value))
				{
					this.OnStatus8Changing(value);
					this.SendPropertyChanging();
					this._Status8 = value;
					this.SendPropertyChanged("Status8");
					this.OnStatus8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value9", DbType="Real")]
		public System.Nullable<float> Value9
		{
			get
			{
				return this._Value9;
			}
			set
			{
				if ((this._Value9 != value))
				{
					this.OnValue9Changing(value);
					this.SendPropertyChanging();
					this._Value9 = value;
					this.SendPropertyChanged("Value9");
					this.OnValue9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status9", DbType="TinyInt")]
		public System.Nullable<byte> Status9
		{
			get
			{
				return this._Status9;
			}
			set
			{
				if ((this._Status9 != value))
				{
					this.OnStatus9Changing(value);
					this.SendPropertyChanging();
					this._Status9 = value;
					this.SendPropertyChanged("Status9");
					this.OnStatus9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value10", DbType="Real")]
		public System.Nullable<float> Value10
		{
			get
			{
				return this._Value10;
			}
			set
			{
				if ((this._Value10 != value))
				{
					this.OnValue10Changing(value);
					this.SendPropertyChanging();
					this._Value10 = value;
					this.SendPropertyChanged("Value10");
					this.OnValue10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status10", DbType="TinyInt")]
		public System.Nullable<byte> Status10
		{
			get
			{
				return this._Status10;
			}
			set
			{
				if ((this._Status10 != value))
				{
					this.OnStatus10Changing(value);
					this.SendPropertyChanging();
					this._Status10 = value;
					this.SendPropertyChanged("Status10");
					this.OnStatus10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value11", DbType="Real")]
		public System.Nullable<float> Value11
		{
			get
			{
				return this._Value11;
			}
			set
			{
				if ((this._Value11 != value))
				{
					this.OnValue11Changing(value);
					this.SendPropertyChanging();
					this._Value11 = value;
					this.SendPropertyChanged("Value11");
					this.OnValue11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status11", DbType="TinyInt")]
		public System.Nullable<byte> Status11
		{
			get
			{
				return this._Status11;
			}
			set
			{
				if ((this._Status11 != value))
				{
					this.OnStatus11Changing(value);
					this.SendPropertyChanging();
					this._Status11 = value;
					this.SendPropertyChanged("Status11");
					this.OnStatus11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value12", DbType="Real")]
		public System.Nullable<float> Value12
		{
			get
			{
				return this._Value12;
			}
			set
			{
				if ((this._Value12 != value))
				{
					this.OnValue12Changing(value);
					this.SendPropertyChanging();
					this._Value12 = value;
					this.SendPropertyChanged("Value12");
					this.OnValue12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status12", DbType="TinyInt")]
		public System.Nullable<byte> Status12
		{
			get
			{
				return this._Status12;
			}
			set
			{
				if ((this._Status12 != value))
				{
					this.OnStatus12Changing(value);
					this.SendPropertyChanging();
					this._Status12 = value;
					this.SendPropertyChanged("Status12");
					this.OnStatus12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value13", DbType="Real")]
		public System.Nullable<float> Value13
		{
			get
			{
				return this._Value13;
			}
			set
			{
				if ((this._Value13 != value))
				{
					this.OnValue13Changing(value);
					this.SendPropertyChanging();
					this._Value13 = value;
					this.SendPropertyChanged("Value13");
					this.OnValue13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status13", DbType="TinyInt")]
		public System.Nullable<byte> Status13
		{
			get
			{
				return this._Status13;
			}
			set
			{
				if ((this._Status13 != value))
				{
					this.OnStatus13Changing(value);
					this.SendPropertyChanging();
					this._Status13 = value;
					this.SendPropertyChanged("Status13");
					this.OnStatus13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value14", DbType="Real")]
		public System.Nullable<float> Value14
		{
			get
			{
				return this._Value14;
			}
			set
			{
				if ((this._Value14 != value))
				{
					this.OnValue14Changing(value);
					this.SendPropertyChanging();
					this._Value14 = value;
					this.SendPropertyChanged("Value14");
					this.OnValue14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status14", DbType="TinyInt")]
		public System.Nullable<byte> Status14
		{
			get
			{
				return this._Status14;
			}
			set
			{
				if ((this._Status14 != value))
				{
					this.OnStatus14Changing(value);
					this.SendPropertyChanging();
					this._Status14 = value;
					this.SendPropertyChanged("Status14");
					this.OnStatus14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value15", DbType="Real")]
		public System.Nullable<float> Value15
		{
			get
			{
				return this._Value15;
			}
			set
			{
				if ((this._Value15 != value))
				{
					this.OnValue15Changing(value);
					this.SendPropertyChanging();
					this._Value15 = value;
					this.SendPropertyChanged("Value15");
					this.OnValue15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status15", DbType="TinyInt")]
		public System.Nullable<byte> Status15
		{
			get
			{
				return this._Status15;
			}
			set
			{
				if ((this._Status15 != value))
				{
					this.OnStatus15Changing(value);
					this.SendPropertyChanging();
					this._Status15 = value;
					this.SendPropertyChanged("Status15");
					this.OnStatus15Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value16", DbType="Real")]
		public System.Nullable<float> Value16
		{
			get
			{
				return this._Value16;
			}
			set
			{
				if ((this._Value16 != value))
				{
					this.OnValue16Changing(value);
					this.SendPropertyChanging();
					this._Value16 = value;
					this.SendPropertyChanged("Value16");
					this.OnValue16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status16", DbType="TinyInt")]
		public System.Nullable<byte> Status16
		{
			get
			{
				return this._Status16;
			}
			set
			{
				if ((this._Status16 != value))
				{
					this.OnStatus16Changing(value);
					this.SendPropertyChanging();
					this._Status16 = value;
					this.SendPropertyChanged("Status16");
					this.OnStatus16Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value17", DbType="Real")]
		public System.Nullable<float> Value17
		{
			get
			{
				return this._Value17;
			}
			set
			{
				if ((this._Value17 != value))
				{
					this.OnValue17Changing(value);
					this.SendPropertyChanging();
					this._Value17 = value;
					this.SendPropertyChanged("Value17");
					this.OnValue17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status17", DbType="TinyInt")]
		public System.Nullable<byte> Status17
		{
			get
			{
				return this._Status17;
			}
			set
			{
				if ((this._Status17 != value))
				{
					this.OnStatus17Changing(value);
					this.SendPropertyChanging();
					this._Status17 = value;
					this.SendPropertyChanged("Status17");
					this.OnStatus17Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value18", DbType="Real")]
		public System.Nullable<float> Value18
		{
			get
			{
				return this._Value18;
			}
			set
			{
				if ((this._Value18 != value))
				{
					this.OnValue18Changing(value);
					this.SendPropertyChanging();
					this._Value18 = value;
					this.SendPropertyChanged("Value18");
					this.OnValue18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status18", DbType="TinyInt")]
		public System.Nullable<byte> Status18
		{
			get
			{
				return this._Status18;
			}
			set
			{
				if ((this._Status18 != value))
				{
					this.OnStatus18Changing(value);
					this.SendPropertyChanging();
					this._Status18 = value;
					this.SendPropertyChanged("Status18");
					this.OnStatus18Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value19", DbType="Real")]
		public System.Nullable<float> Value19
		{
			get
			{
				return this._Value19;
			}
			set
			{
				if ((this._Value19 != value))
				{
					this.OnValue19Changing(value);
					this.SendPropertyChanging();
					this._Value19 = value;
					this.SendPropertyChanged("Value19");
					this.OnValue19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status19", DbType="TinyInt")]
		public System.Nullable<byte> Status19
		{
			get
			{
				return this._Status19;
			}
			set
			{
				if ((this._Status19 != value))
				{
					this.OnStatus19Changing(value);
					this.SendPropertyChanging();
					this._Status19 = value;
					this.SendPropertyChanged("Status19");
					this.OnStatus19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value20", DbType="Real")]
		public System.Nullable<float> Value20
		{
			get
			{
				return this._Value20;
			}
			set
			{
				if ((this._Value20 != value))
				{
					this.OnValue20Changing(value);
					this.SendPropertyChanging();
					this._Value20 = value;
					this.SendPropertyChanged("Value20");
					this.OnValue20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status20", DbType="TinyInt")]
		public System.Nullable<byte> Status20
		{
			get
			{
				return this._Status20;
			}
			set
			{
				if ((this._Status20 != value))
				{
					this.OnStatus20Changing(value);
					this.SendPropertyChanging();
					this._Status20 = value;
					this.SendPropertyChanged("Status20");
					this.OnStatus20Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value21", DbType="Real")]
		public System.Nullable<float> Value21
		{
			get
			{
				return this._Value21;
			}
			set
			{
				if ((this._Value21 != value))
				{
					this.OnValue21Changing(value);
					this.SendPropertyChanging();
					this._Value21 = value;
					this.SendPropertyChanged("Value21");
					this.OnValue21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status21", DbType="TinyInt")]
		public System.Nullable<byte> Status21
		{
			get
			{
				return this._Status21;
			}
			set
			{
				if ((this._Status21 != value))
				{
					this.OnStatus21Changing(value);
					this.SendPropertyChanging();
					this._Status21 = value;
					this.SendPropertyChanged("Status21");
					this.OnStatus21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value22", DbType="Real")]
		public System.Nullable<float> Value22
		{
			get
			{
				return this._Value22;
			}
			set
			{
				if ((this._Value22 != value))
				{
					this.OnValue22Changing(value);
					this.SendPropertyChanging();
					this._Value22 = value;
					this.SendPropertyChanged("Value22");
					this.OnValue22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status22", DbType="TinyInt")]
		public System.Nullable<byte> Status22
		{
			get
			{
				return this._Status22;
			}
			set
			{
				if ((this._Status22 != value))
				{
					this.OnStatus22Changing(value);
					this.SendPropertyChanging();
					this._Status22 = value;
					this.SendPropertyChanged("Status22");
					this.OnStatus22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value23", DbType="Real")]
		public System.Nullable<float> Value23
		{
			get
			{
				return this._Value23;
			}
			set
			{
				if ((this._Value23 != value))
				{
					this.OnValue23Changing(value);
					this.SendPropertyChanging();
					this._Value23 = value;
					this.SendPropertyChanged("Value23");
					this.OnValue23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status23", DbType="TinyInt")]
		public System.Nullable<byte> Status23
		{
			get
			{
				return this._Status23;
			}
			set
			{
				if ((this._Status23 != value))
				{
					this.OnStatus23Changing(value);
					this.SendPropertyChanging();
					this._Status23 = value;
					this.SendPropertyChanged("Status23");
					this.OnStatus23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value24", DbType="Real")]
		public System.Nullable<float> Value24
		{
			get
			{
				return this._Value24;
			}
			set
			{
				if ((this._Value24 != value))
				{
					this.OnValue24Changing(value);
					this.SendPropertyChanging();
					this._Value24 = value;
					this.SendPropertyChanged("Value24");
					this.OnValue24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status24", DbType="TinyInt")]
		public System.Nullable<byte> Status24
		{
			get
			{
				return this._Status24;
			}
			set
			{
				if ((this._Status24 != value))
				{
					this.OnStatus24Changing(value);
					this.SendPropertyChanging();
					this._Status24 = value;
					this.SendPropertyChanged("Status24");
					this.OnStatus24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value25", DbType="Real")]
		public System.Nullable<float> Value25
		{
			get
			{
				return this._Value25;
			}
			set
			{
				if ((this._Value25 != value))
				{
					this.OnValue25Changing(value);
					this.SendPropertyChanging();
					this._Value25 = value;
					this.SendPropertyChanged("Value25");
					this.OnValue25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status25", DbType="TinyInt")]
		public System.Nullable<byte> Status25
		{
			get
			{
				return this._Status25;
			}
			set
			{
				if ((this._Status25 != value))
				{
					this.OnStatus25Changing(value);
					this.SendPropertyChanging();
					this._Status25 = value;
					this.SendPropertyChanged("Status25");
					this.OnStatus25Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value26", DbType="Real")]
		public System.Nullable<float> Value26
		{
			get
			{
				return this._Value26;
			}
			set
			{
				if ((this._Value26 != value))
				{
					this.OnValue26Changing(value);
					this.SendPropertyChanging();
					this._Value26 = value;
					this.SendPropertyChanged("Value26");
					this.OnValue26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status26", DbType="TinyInt")]
		public System.Nullable<byte> Status26
		{
			get
			{
				return this._Status26;
			}
			set
			{
				if ((this._Status26 != value))
				{
					this.OnStatus26Changing(value);
					this.SendPropertyChanging();
					this._Status26 = value;
					this.SendPropertyChanged("Status26");
					this.OnStatus26Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value27", DbType="Real")]
		public System.Nullable<float> Value27
		{
			get
			{
				return this._Value27;
			}
			set
			{
				if ((this._Value27 != value))
				{
					this.OnValue27Changing(value);
					this.SendPropertyChanging();
					this._Value27 = value;
					this.SendPropertyChanged("Value27");
					this.OnValue27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status27", DbType="TinyInt")]
		public System.Nullable<byte> Status27
		{
			get
			{
				return this._Status27;
			}
			set
			{
				if ((this._Status27 != value))
				{
					this.OnStatus27Changing(value);
					this.SendPropertyChanging();
					this._Status27 = value;
					this.SendPropertyChanged("Status27");
					this.OnStatus27Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value28", DbType="Real")]
		public System.Nullable<float> Value28
		{
			get
			{
				return this._Value28;
			}
			set
			{
				if ((this._Value28 != value))
				{
					this.OnValue28Changing(value);
					this.SendPropertyChanging();
					this._Value28 = value;
					this.SendPropertyChanged("Value28");
					this.OnValue28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status28", DbType="TinyInt")]
		public System.Nullable<byte> Status28
		{
			get
			{
				return this._Status28;
			}
			set
			{
				if ((this._Status28 != value))
				{
					this.OnStatus28Changing(value);
					this.SendPropertyChanging();
					this._Status28 = value;
					this.SendPropertyChanged("Status28");
					this.OnStatus28Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value29", DbType="Real")]
		public System.Nullable<float> Value29
		{
			get
			{
				return this._Value29;
			}
			set
			{
				if ((this._Value29 != value))
				{
					this.OnValue29Changing(value);
					this.SendPropertyChanging();
					this._Value29 = value;
					this.SendPropertyChanged("Value29");
					this.OnValue29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status29", DbType="TinyInt")]
		public System.Nullable<byte> Status29
		{
			get
			{
				return this._Status29;
			}
			set
			{
				if ((this._Status29 != value))
				{
					this.OnStatus29Changing(value);
					this.SendPropertyChanging();
					this._Status29 = value;
					this.SendPropertyChanged("Status29");
					this.OnStatus29Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value30", DbType="Real")]
		public System.Nullable<float> Value30
		{
			get
			{
				return this._Value30;
			}
			set
			{
				if ((this._Value30 != value))
				{
					this.OnValue30Changing(value);
					this.SendPropertyChanging();
					this._Value30 = value;
					this.SendPropertyChanged("Value30");
					this.OnValue30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status30", DbType="TinyInt")]
		public System.Nullable<byte> Status30
		{
			get
			{
				return this._Status30;
			}
			set
			{
				if ((this._Status30 != value))
				{
					this.OnStatus30Changing(value);
					this.SendPropertyChanging();
					this._Status30 = value;
					this.SendPropertyChanged("Status30");
					this.OnStatus30Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value31", DbType="Real")]
		public System.Nullable<float> Value31
		{
			get
			{
				return this._Value31;
			}
			set
			{
				if ((this._Value31 != value))
				{
					this.OnValue31Changing(value);
					this.SendPropertyChanging();
					this._Value31 = value;
					this.SendPropertyChanged("Value31");
					this.OnValue31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status31", DbType="TinyInt")]
		public System.Nullable<byte> Status31
		{
			get
			{
				return this._Status31;
			}
			set
			{
				if ((this._Status31 != value))
				{
					this.OnStatus31Changing(value);
					this.SendPropertyChanging();
					this._Status31 = value;
					this.SendPropertyChanged("Status31");
					this.OnStatus31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value32", DbType="Real")]
		public System.Nullable<float> Value32
		{
			get
			{
				return this._Value32;
			}
			set
			{
				if ((this._Value32 != value))
				{
					this.OnValue32Changing(value);
					this.SendPropertyChanging();
					this._Value32 = value;
					this.SendPropertyChanged("Value32");
					this.OnValue32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status32", DbType="TinyInt")]
		public System.Nullable<byte> Status32
		{
			get
			{
				return this._Status32;
			}
			set
			{
				if ((this._Status32 != value))
				{
					this.OnStatus32Changing(value);
					this.SendPropertyChanging();
					this._Status32 = value;
					this.SendPropertyChanged("Status32");
					this.OnStatus32Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OPERATOR")]
	public partial class OPERATOR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public OPERATOR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATUS")]
	public partial class STATUS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _Id;
		
		private string _Name;
		
		private bool _Valid;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(short value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnValidChanging(bool value);
    partial void OnValidChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public STATUS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valid", DbType="Bit NOT NULL")]
		public bool Valid
		{
			get
			{
				return this._Valid;
			}
			set
			{
				if ((this._Valid != value))
				{
					this.OnValidChanging(value);
					this.SendPropertyChanging();
					this._Valid = value;
					this.SendPropertyChanged("Valid");
					this.OnValidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
